name: cumpri
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  drift: ^2.28.1
  drift_flutter: ^0.2.5
  flutter:
    sdk: flutter
  flutter_mobx: ^2.3.0
  mobx: ^2.5.0
  mobx_codegen: ^2.7.2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.7.0
  drift_dev: ^2.28.1

flutter:
  uses-material-design: true